green/urls.py
from django.urls import path
from django.views.generic import TemplateView

from green.views import Comment
from . import views
from .views import Comment

app_name = "green"

urlpatterns = [
    path("",views.home, name="home.html"),
    path("Basica_Matematicas_primero/",views.m1, name="Basica_Matematicas_primero"),
    path("Basica_Lenguaje_primero/",views.l1, name="Basica_Lenguaje_primero"),
    path("Basica_Ciencias_primero/",views.c1, name="Basica_Ciencias_primero"),
    path("Basica_Historia_primero/",views.h1, name="Basica_Historia_primero"),
    path("Basica_Otros_primero/",views.o1, name="Basica_Otros_primero"),
    path("Basica_Ingles_primero/",views.i1, name="Basica_Ingles_primero"),
    path("Basica_Matematicas_segundo/",views.m2, name="Basica_Matematicas_segundo"),
    path("Basica_Lenguaje_segundo/",views.l2, name="Basica_Lenguaje_segundo"),
    path("Basica_Ciencias_segundo/",views.c2, name="Basica_Ciencias_segundo"),
    path("Basica_Historia_segundo/",views.h2, name="Basica_Historia_segundo"),
    path("Basica_Otros_segundo/",views.o2, name="Basica_Otros_segundo"),
    path("Basica_Ingles_segundo/",views.i2, name="Basica_Ingles_segundo"),
    path("Basica_Matematicas_tercero/",views.m3, name="Basica_Matematicas_tercero"),
    path("Basica_Lenguaje_tercero/",views.l3, name="Basica_Lenguaje_tercero"),
    path("Basica_Ciencias_tercero/",views.c3, name="Basica_Ciencias_tercero"),
    path("Basica_Historia_tercero/",views.h3, name="Basica_Historia_tercero"),
    path("Basica_Otros_tercero/",views.o3, name="Basica_Otros_tercero"),
    path("Basica_Ingles_tercero/",views.i3, name="Basica_Ingles_tercero"),
    path("Basica_Matematicas_cuarto/",views.m4, name="Basica_Matematicas_cuarto"),
    path("Basica_Lenguaje_cuarto/",views.l4, name="Basica_Lenguaje_cuarto"),
    path("Basica_Ciencias_cuarto/",views.c4, name="Basica_Ciencias_cuarto"),
    path("Basica_Historia_cuarto/",views.h4, name="Basica_Historia_cuarto"),
    path("Basica_Otros_cuarto/",views.o4, name="Basica_Otros_cuarto"),
    path("Basica_Ingles_cuarto/",views.i4, name="Basica_Ingles_cuarto"),
    path("Basica_Matematicas_quinto/",views.m5, name="Basica_Matematicas_quinto"),
    path("Basica_Lenguaje_quinto/",views.l5, name="Basica_Lenguaje_quinto"),
    path("Basica_Ciencias_quinto/",views.c5, name="Basica_Ciencias_quinto"),
    path("Basica_Historia_quinto/",views.h5, name="Basica_Historia_quinto"),
    path("Basica_Otros_quinto/",views.o5, name="Basica_Otros_quinto"),
    path("Basica_Ingles_quinto/",views.i5, name="Basica_Ingles_quinto"),
    path("Basica_Matematicas_sexto/",views.m6, name="Basica_Matematicas_sexto"),
    path("Basica_Lenguaje_sexto/",views.l6, name="Basica_Lenguaje_sexto"),
    path("Basica_Ciencias_sexto/",views.c6, name="Basica_Ciencias_sexto"),
    path("Basica_Historia_sexto/",views.h6, name="Basica_Historia_sexto"),
    path("Basica_Otros_sexto/",views.o6, name="Basica_Otros_sexto"),
    path("Basica_Ingles_sexto/",views.i6, name="Basica_Ingles_sexto"),
    path("Basica_Matematicas_septimo/",views.m7, name="Basica_Matematicas_septimo"),
    path("Basica_Lenguaje_septimo/",views.l7, name="Basica_Lenguaje_septimo"),
    path("Basica_Ciencias_septimo/",views.c7, name="Basica_Ciencias_septimo"),
    path("Basica_Historia_septimo/",views.h7, name="Basica_Historia_septimo"),
    path("Basica_Otros_septimo/",views.o7, name="Basica_Otros_septimo"),
    path("Basica_Ingles_septimo/",views.i7, name="Basica_Ingles_septimo"),
    path("Basica_Matematicas_octavo/",views.m8, name="Basica_Matematicas_octavo"),
    path("Basica_Lenguaje_octavo/",views.l8, name="Basica_Lenguaje_octavo"),
    path("Basica_Ciencias_octavo/",views.c8, name="Basica_Ciencias_octavo"),
    path("Basica_Historia_octavo/",views.h8, name="Basica_Historia_octavo"),
    path("Basica_Otros_octavo/",views.o8, name="Basica_Otros_octavo"),
    path("Basica_Ingles_octavo/",views.i8, name="Basica_Ingles_octavo"),
    path("media_biologia_primero", views.bI, name="media_biologia_primero"),
    path("media_fisica_primero", views.fI, name="media_fisica_primero"),
    path("media_historia_primero", views.hI, name="media_historia_primero"),
    path("media_ingles_primero", views.iI, name="media_ingles_primero"),
    path("media_lenguaje_primero", views.lI, name="media_lenguaje_primero"),
    path("media_matematicas_primero", views.mI, name="media_matematicas_primero"),
    path("media_otros_primero", views.oI, name="media_otros_primero"),
    path("media_quimica_primero", views.qI, name="media_quimica_primero"),
    path("media_biologia_segundo", views.bII, name="media_biologia_segundo"),
    path("media_fisica_segundo", views.fII, name="media_fisica_segundo"),
    path("media_historia_segundo", views.hII, name="media_historia_segundo"),
    path("media_ingles_segundo", views.iII, name="media_ingles_segundo"),
    path("media_lenguaje_segundo", views.lII, name="media_lenguaje_segundo"),
    path("media_matematicas_segundo", views.mII, name="media_matematicas_segundo"),
    path("media_otros_segundo", views.oII, name="media_otros_segundo"),
    path("media_quimica_segundo", views.qII, name="media_quimica_segundo"),
    path("media_biologia_tercero", views.bIII, name="media_biologia_tercero"),
    path("media_fisica_tercero", views.fIII, name="media_fisica_tercero"),
    path("media_historia_tercero", views.hIII, name="media_historia_tercero"),
    path("media_ingles_tercero", views.iIII, name="media_ingles_tercero"),
    path("media_lenguaje_tercero", views.lIII, name="media_lenguaje_tercero"),
    path("media_matematicas_tercero", views.mIII, name="media_matematicas_tercero"),
    path("media_otros_tercero", views.oIII, name="media_otros_tercero"),
    path("media_quimica_tercero", views.qIII, name="media_quimica_tercero"),
    path("media_quimicaA_tercero", views.qaIII, name="media_quimicaA_tercero"),
    path("media_biologiaA_tercero", views.baIII, name="media_biologiaA_tercero"),
    path("media_fisicaA_tercero", views.faIII, name="media_fisicaA_tercero"),
    path("media_matematicasA_tercero", views.maIII, name="media_matematicasA_tercero"),

    path("media_biologia_cuarto", views.bIV, name="media_biologia_cuarto"),
    path("media_fisica_cuarto", views.fIV, name="media_fisica_cuarto"),
    path("media_historia_cuarto", views.hIV, name="media_historia_cuarto"),
    path("media_ingles_cuarto", views.iIV, name="media_ingles_cuarto"),
    path("media_lenguaje_cuarto", views.lIV, name="media_lenguaje_cuarto"),
    path("media_matematicas_cuarto", views.mIV, name="media_matematicas_cuarto"),
    path("media_otros_cuarto", views.oIV, name="media_otros_cuarto"),
    path("media_quimica_cuarto", views.qIV, name="media_quimica_cuarto"),
    path("media_quimicaA_cuarto", views.qaIV, name="media_quimicaA_cuarto"),
    path("media_biologiaA_cuarto", views.baIV, name="media_biologiaA_cuarto"),
    path("media_fisicaA_cuarto", views.faIV, name="media_fisicaA_cuarto"),
    path("media_matematicasA_cuarto", views.maIV, name="media_matematicasA_cuarto"),
    path("media_matematicasA_cuarto", views.maIV, name="media_matematicasA_cuarto"),

    path("pdt_biologia", views.b, name="pdt_biologia"),
    path("pdt_fisica", views.f, name="pdt_fisica"),
    path("pdt_historia", views.h, name="pdt_historia"),
    path("pdt_lenguaje", views.l, name="pdt_lenguaje"),
    path("pdt_matematicas", views.m, name="pdt_matematicas"),
    path("pdt_otros", views.o, name="pdt_otros"),
    path("pdt_quimica", views.q, name="pdt_quimica"),
    path("pdt_quimicaA", views.qa, name="pdt_quimicaA"),
    path("pdt_biologiaA", views.ba, name="pdt_biologiaA"),
    path("pdt_fisicaA", views.fa, name="pdt_fisicaA"),
    path("pdt_matematicasA", views.ma, name="pdt_matematicasA"),
    
    path('post/', views.create_post, name= 'create_post'),
    
    path('post/<int:pk>', views.Comment, name='post_detail'),
]

trabajo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("green.urls", namespace="green")),
    path("",include("users.urls",namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path("follow/<slug:slug>", views.follow, name='follow'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path("followers/", views.followers_view, name="followers"),
    path("following/", views.following_view, name="following"),
    path("followers_user/", views.followers_user_view, name="followers_user"),
    path("following_user/", views.following_user_view, name="following_user"),
    path("Posts",views.post_profile, name="post_profile"),
    path("posts",views.post_user, name="post_user"),
]

users/forms.py
from django import forms


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'loginEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'id': 'loginPassword',
            'type': 'password',
            'class': 'form-control',
        })
    )


class UserSignUpForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'signupEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    nombre = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))

    ciudad = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'signupPassword',
                'type': 'password',
                'class': 'form-control'
            }
        ))

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control'
            }
        ))

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Las Contraseñas no coinciden')
        return cd['password2']

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from green.models import Post
from .forms import UserLoginForm, UserSignUpForm


def login_view(request):
    login_form = UserLoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Has iniciado sesion correctamente')
            return redirect('green:home.html')
        else:
            messages.warning(
                request, 'Correo Electronico o Contrasena invalida')
            return redirect('green:home.html')

    messages.error(request, 'Formulario Invalido')
    return redirect('green:home.html')


def signup_view(request):
    signup_form = UserSignUpForm(request.POST or None)
    if signup_form.is_valid():
        email = signup_form.cleaned_data.get('email')
        nombre = signup_form.cleaned_data.get('nombre')
        ciudad = signup_form.cleaned_data.get('ciudad')
        password = signup_form.cleaned_data.get('password')
        try:
            user = get_user_model().objects.create(
                email=email,
                nombre=nombre,
                ciudad=ciudad,
                password=make_password(password),
                is_active=True
            )
            login(request, user)
            return redirect('green:home.html')

        except Exception as e:
            print(e)
            return JsonResponse({'detail': f'{e}'})


def logout_view(request):
    logout(request)
    return redirect('green:home.html')


@login_required(login_url='green:home.html')
def profile_view(request):
    return render(request, 'users/profile.html')


def user_detail(request, slug):
    user = get_object_or_404(get_user_model(), slug=slug)
    is_follower = False
    try:
        if user.is_follower(request.user):
            is_follower = True
    except:
        messages.warning(
            request, 'Debes Iniciar sesion para mas funcionalidades')
        return redirect("green:home.html")

    return render(request, 'users/user_detail.html', {'user_detail': user, "is_follower": is_follower})


@login_required(login_url='green:home.html')
def follow(request, slug):
    to_follow = get_object_or_404(get_user_model(), slug=slug)
    if to_follow.is_follower(request.user):
        to_follow.followers.remove(request.user)
    else:
        to_follow.followers.add(request.user)
    to_follow.save
    return redirect(to_follow)





@login_required(login_url='users:profile.html')
def following_view(request):
    return render(request, 'users/seguidos_profile.html')


@login_required(login_url='users:profile.html')
def followers_view(request):
    if request.user.is_authenticated:
        user = request.user
        data = user.followers.all()
    return render(request, 'users/seguidores_profile.html')


@login_required(login_url='users:profile.html')
def followers_user_view(request):
    return render(request, 'users/seguidores_user.html')


@login_required(login_url='users:profile.html')
def following_user_view(request):
    return render(request, 'users/seguidos_user.html', { 'user_detail': user})



@login_required(login_url='green:home.html')
def post_profile(request):
    data = Post.objects.all()
    return render(request, "users/post_profile.html", {"posts": data})


@login_required(login_url='green:home.html')
def post_user(request):
    data = Post.objects.all()

    return render(request, "users/post_user.html", { "user_detail": user, "posts": data})

templates/users/login.html
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
  
          <ul class="nav nav-pills nav-justified mb-3">
            <li class="nav-item">
              <a class="nav-link active show" data-mdb-toggle="pill" href="#navbarLogin-login" role="tab">
                Iniciar Sesion</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-mdb-toggle="pill" href="#navbarLogin-signup" role="tab">Registrarse</a>
            </li>
          </ul>
  
          <div class="tab-content" id="tab-content">
            <div class="tab-pane fade show active" id="navbarLogin-login" role="tabpanel">
              <form id="login" class="text-center" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
  
                <div class="form-outline form-auth-md mb-4">
                  {{ loginForm.email }}
                  <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
                </div>
  
                <div class="form-outline form-auth-md mb-4">
                  {{ loginForm.password }}
                  <label class="form-label" style="margin-left: 0px;">Contraseña</label>
                </div>
  
  
  
                <button type="submit" class="btn btn-primary btn-block mb-4">Iniciar</button>
              </form>
            </div>
  
  
            <div class="tab-pane fade" id="navbarLogin-signup" role="tabpanel">
              <form id="register" class="text-center" action="{% url 'users:signup'%}" method="post">
                {% csrf_token %}
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.email}}
                  <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
                </div>
  
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.nombre }}
                  <label class="form-label" style="margin-left: 0px;">Nombre</label>
                </div>

                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.ciudad }}
                  <label class="form-label" style="margin-left: 0px;">Ciudad</label>
                </div>
  
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.password }}
                  <label class="form-label" style="margin-left: 0px;">Your password
                  </label>
                </div>
  
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.password2 }}
                  <label class="form-label" style="margin-left: 0px;">Repeat password
                  </label>
  
                </div>
  
                <button class="btn btn-primary btn-block mb-3" type="submit">Registrar</button>
              </form>
  
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </div>

templates/users/post_profile.html
{% extends "../plantilla2.html" %}

{% block content %}
<div class='container col-md-8 col-xl-6'>
  <h1 class='text-center my-4'>Tus Publicaciones</h1>
  
  {% for post in posts %}
  {% if post.author_id == user.id%}
    <div class="card shadow border mb-3">
      <img src={{post.image.url}} class="card-img-top" />

      <div class="card-body">
        <a href={{ post.author.get_absolute_url }}>
         <h5 class="card-title">{{post.author}}</h5>
        </a>
        <p class="card-text">
         {{post.description}}
        </p>
      </div>

      <div class='card-footer'>
       <p class="card-text">
          <small class="text-muted">{{post.published}}</small>
        </p>
      </div>

    </div>
  {% endif %}
  {% endfor %}
  {% endblock %}
</div>

templates/users/post_user.html
{% extends "../plantilla2.html" %}

{{% block content %}
<div class='container col-md-8 col-xl-6'>
  <h1 class='text-center my-4 '>Libros publicados por {{ user_detail.nombre}} </h1>

  {% endblock %}
</div>

templates/users/profile.html
{% extends "../plantilla2.html" %}

{% block content %}
<div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
  <div class="card shadow-4-strong mb-3">
    <div class="row g-0">
      <div class="col-md-5">
        <img src={{ user.profile_pic.url }} alt="..." class="img-fluid rounded" />
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <div class='row justify-content-center'>
            <h4 class="col-12 card-title text-center mb-4">{{ user.nombre}}</h4>
            <a class="col-4 textcenter" href={% url "users:post_profile"%}>Publicaciones</a>
            <a class="col-4 textcenter" href={% url "users:followers"%}>Seguidores</a>
            <a class="col-4 textcenter" href={% url "users:following"%}>seguidos</a>

            <p class="col-3 text-center"><strong>{{ user.count_posts }}</strong></p>
            <p class="col-3 text-center"><strong>{{ user.followers.all|length }}</strong></p>
            <p class="col-3 text-center"><strong>{{ user.count_following }}</strong></p>


            <p class="card-text text-center mb-5">{{ user.bio }}</p>

            <a class='btn btn-danger btn-rounded col-5' href={% url 'users:logout'%}>
              Cerrar Sesion
            </a>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>
jofeda inc
{% endblock %}
jofeda inc

templates/users/seguidores_profile.html
{% extends "../plantilla2.html" %}

{% block content %}
<div class='container col-md-8 col-xl-6'>
    <h1 class='text-center my-4'>Seguidores</h1>
    
        <p class="text-center"><strong></strong></p>
    
{% endblock %}
</div>

templates/users/seguidores_user.html
{% extends "../plantilla2.html" %}

{% block content %}
<div class='container col-md-8 col-xl-6'>
    <h1 class='text-center my-4'>Seguidores</h1>
    
        <p class="text-center"><strong></strong></p>
    
{% endblock %}
</div>

templates/users/seguidos_profile.html
{% extends "../plantilla2.html" %}

{% block content %}
<div class='container col-md-8 col-xl-6'>
    <h1 class='text-center my-4'>Seguidos</h1>
    
        <p class="text-center"><strong></strong></p>
    
{% endblock %}
</div>

templates/users/seguidos_user.html
{% extends "../plantilla2.html" %}

{% block content %}
<div class='container col-md-8 col-xl-6'>
    <h1 class='text-center my-4'>Seguidos</h1>
    
        <p class="text-center"><strong></strong></p>
    
{% endblock %}
</div>

templates/users/user_detail.html
{% extends "../plantilla2.html" %}

{% block content %}
<div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
  <div class="card shadow-4-strong mb-3">
    <div class="row g-0">
      <div class="col-md-5">
        <img src={{ user_detail.profile_pic.url }} alt="..." class="img-fluid rounded" />
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <div class='row justify-content-center'>
            <h4 class="col-12 card-title text-center mb-4">{{ user_detail.nombre}} </h4>
            <p class="col-12 text-center"><strong>{{ user_detail.ciudad }}</strong></p>
            <a class="col-4 textcenter" href={{ post.author.get_absolute_url }}{% url "users:post_user"%}>Publicaciones</p>
            <a class="col-4 textcenter" href={% url "users:followers_user"%}>Seguidores</a>
            <a class="col-4 textcenter" href={% url "users:following_user"%}>seguidos</a>

            <p class="col-4 text-center"><strong>{{ user_detail.count_posts }}</strong></p>
            <p class="col-4 text-center"><strong>{{ user_detail.followers.all|length }}</strong></p>
            <p class="col-4 text-center"><strong>{{ user_detail.count_following }}</strong></p>
            
           

            {% if is_follower %}
            <a type="button" class="btn btn-secondary btn-rounded col-5"
              href={% url 'users:follow' slug=user_detail.slug %}>Dejar de Seguir</a>
            {% elif user_detail != user and user.email %}
            <a type="button" id='follow' class="btn btn-primary btn-rounded col-5"
              href={% url 'users:follow' slug=user_detail.slug %}>Seguir</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}